# NETTOYAGE DES DONNEES
    Encadré par : Pr. Amal OURDOU
    Réalisé par : - Kamal CHERKAOUI
                  - Yasser ZARHLOUL
                  - Achraf AISSY
                  - Zakaria EL FATHI
  
  ><h6>IID2- ENSA de Khouribga- 2022/2023</h6>
  
  ---

# Librairies / Datasets

<h5> Importation des librairies necessaires

In [1]:
import pandas as pd
import numpy as np

<h5> Datasets (Cambridge.csv & Boston.csv )

In [2]:
df_boston = pd.read_csv("datasets/boston.csv")
df_cambridge = pd.read_csv("datasets/cambridge.csv")

---
# Data sets preview

In [3]:
print('Bostons dataset has %d rows and %d columns.' % df_boston.shape)
print('_'*50)
print('Cambridges dataset has %d rows and %d columns.' % df_cambridge.shape)

Bostons dataset has 3507 rows and 106 columns.
__________________________________________________
Cambridges dataset has 1277 rows and 106 columns.

In [4]:
df_cambridge.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,8521,https://www.airbnb.com/rooms/8521,20191126082128,2019-11-26,SunsplashedSerenity near Harvard $1300/wk flex...,"An elegant, sun-splashed, 2 bedroom (+2offices...","An elegant, sun-splashed, 2+ bedroom apartment...","An elegant, sun-splashed, 2 bedroom (+2offices...",none,Huron Village is known for its charm. We have...,...,f,f,strict_14_with_grace_period,f,f,3,3,0,0,0.26
1,11169,https://www.airbnb.com/rooms/11169,20191126082128,2019-11-26,Lovely Studio Room: Thu-Mons Near Universities!,Large sunny room which comfortably fits a coup...,"We have a peaceful, large, sunny room w/ attac...",Large sunny room which comfortably fits a coup...,none,The neighborhood is quiet and friendly and our...,...,f,f,strict_14_with_grace_period,t,t,4,1,3,0,1.22
2,11945,https://www.airbnb.com/rooms/11945,20191126082128,2019-11-26,Near Harvard: Safe & Lovely Room,Room next to kitchen and living room in wonder...,"Quiet peaceful room w/shared marble bath, wifi...",Room next to kitchen and living room in wonder...,none,Amazing neighborhood: Quiet yet close walk to ...,...,f,f,strict_14_with_grace_period,t,t,4,1,3,0,0.27
3,19581,https://www.airbnb.com/rooms/19581,20191126082128,2019-11-26,"Furnished suite, Windsor","Welcome to Area IV! We are located, convenient...","Furnished suite at the Windsor Inn, Cambridge....","Welcome to Area IV! We are located, convenient...",none,NaN,...,f,f,strict_14_with_grace_period,f,f,3,0,3,0,0.05
4,22006,https://www.airbnb.com/rooms/22006,20191126082128,2019-11-26,B & B near Harvard's Quad Houses,"Two comfortable guest rooms in quiet, tree-fil...","Comfortable, convenient B&B at the north end o...","Two comfortable guest rooms in quiet, tree-fil...",none,"We're in a beautiful neighborhood, with nearby...",...,f,f,moderate,f,f,1,0,1,0,0.89

In [5]:
df_boston.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,5506,https://www.airbnb.com/rooms/5506,20191204162830,2019-12-04,**$79 Special ** Private! Minutes to center!,"Private guest room with private bath, You do n...",**THE BEST Value in BOSTON!!*** PRIVATE GUEST ...,"Private guest room with private bath, You do n...",none,"Peacful, Architecturally interesting, historic...",...,t,f,strict_14_with_grace_period,f,f,6,6,0,0,0.81
1,6695,https://www.airbnb.com/rooms/6695,20191204162830,2019-12-04,$99 Special!! Home Away! Condo,"Comfortable, Fully Equipped private apartment...",** WELCOME *** FULL PRIVATE APARTMENT In a His...,"Comfortable, Fully Equipped private apartment...",none,"Peaceful, Architecturally interesting, histori...",...,t,f,strict_14_with_grace_period,f,f,6,6,0,0,0.91
2,8789,https://www.airbnb.com/rooms/8789,20191204162830,2019-12-04,Curved Glass Studio/1bd facing Park,"Bright, 1 bed with curved glass windows facing...",Fully Furnished studio with enclosed bedroom. ...,"Bright, 1 bed with curved glass windows facing...",none,Beacon Hill is a historic neighborhood filled ...,...,f,f,strict_14_with_grace_period,f,f,10,10,0,0,0.37
3,10730,https://www.airbnb.com/rooms/10730,20191204162830,2019-12-04,Bright 1bed facing Golden Dome,"Bright, spacious unit, new galley kitchen, new...",Bright one bed facing the golden dome of the S...,"Bright, spacious unit, new galley kitchen, new...",none,Beacon Hill is located downtown and is conveni...,...,f,f,strict_14_with_grace_period,f,f,10,10,0,0,0.24
4,10811,https://www.airbnb.com/rooms/10811,20191204162830,2019-12-04,"Back Bay Apt Studio-3 blocks to Pru center & ""T""",Stunning Back Bay furnished studio apartment. ...,"Back Bay Studio Apt - Private bath, A/C, Cabl...",Stunning Back Bay furnished studio apartment. ...,none,A one-square mile neighborhood that is arguabl...,...,f,f,strict_14_with_grace_period,f,f,7,7,0,0,0.19

---
# Dropping columns that are of no use

### Formatting dataframe's columns names to UpperCase

In [6]:
df_boston.columns = df_boston.columns.str.upper()

In [7]:
df_cambridge.columns = df_cambridge.columns.str.upper()

### Dropping irrelevant columns:

In [8]:
df_boston = df_boston.drop(['ID', 'LISTING_URL', 'SCRAPE_ID', 'LAST_SCRAPED', 'NAME', 'SUMMARY', 'SPACE', 'DESCRIPTION', 'EXPERIENCES_OFFERED', 'NEIGHBORHOOD_OVERVIEW', 'NOTES', 'TRANSIT', 'ACCESS', 'INTERACTION', 'HOUSE_RULES', 'THUMBNAIL_URL', 'MEDIUM_URL', 'PICTURE_URL', 'XL_PICTURE_URL', 'HOST_URL', 'HOST_NAME', 'HOST_SINCE', 'HOST_LOCATION', 'HOST_ABOUT', 'HOST_THUMBNAIL_URL', 'HOST_PICTURE_URL', 'HOST_NEIGHBOURHOOD', 'HOST_VERIFICATIONS', 'STREET', 'NEIGHBOURHOOD', 'NEIGHBOURHOOD_CLEANSED', 'NEIGHBOURHOOD_GROUP_CLEANSED', 'CITY', 'STATE', 'ZIPCODE', 'MARKET', 'SMART_LOCATION', 'COUNTRY_CODE', 'COUNTRY', 'IS_LOCATION_EXACT', 'CALENDAR_UPDATED', 'HAS_AVAILABILITY', 'CALENDAR_LAST_SCRAPED', 'REQUIRES_LICENSE', 'LICENSE', 'JURISDICTION_NAMES', 'REQUIRE_GUEST_PROFILE_PICTURE', 'REQUIRE_GUEST_PHONE_VERIFICATION', 'CALCULATED_HOST_LISTINGS_COUNT', 'CALCULATED_HOST_LISTINGS_COUNT_ENTIRE_HOMES', 'CALCULATED_HOST_LISTINGS_COUNT_PRIVATE_ROOMS', 'CALCULATED_HOST_LISTINGS_COUNT_SHARED_ROOMS'], axis=1)
print(df_boston.columns.to_list())

['HOST_ID', 'HOST_RESPONSE_TIME', 'HOST_RESPONSE_RATE', 'HOST_ACCEPTANCE_RATE', 'HOST_IS_SUPERHOST', 'HOST_LISTINGS_COUNT', 'HOST_TOTAL_LISTINGS_COUNT', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'LATITUDE', 'LONGITUDE', 'PROPERTY_TYPE', 'ROOM_TYPE', 'ACCOMMODATES', 'BATHROOMS', 'BEDROOMS', 'BEDS', 'BED_TYPE', 'AMENITIES', 'SQUARE_FEET', 'PRICE', 'WEEKLY_PRICE', 'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE', 'GUESTS_INCLUDED', 'EXTRA_PEOPLE', 'MINIMUM_NIGHTS', 'MAXIMUM_NIGHTS', 'MINIMUM_MINIMUM_NIGHTS', 'MAXIMUM_MINIMUM_NIGHTS', 'MINIMUM_MAXIMUM_NIGHTS', 'MAXIMUM_MAXIMUM_NIGHTS', 'MINIMUM_NIGHTS_AVG_NTM', 'MAXIMUM_NIGHTS_AVG_NTM', 'AVAILABILITY_30', 'AVAILABILITY_60', 'AVAILABILITY_90', 'AVAILABILITY_365', 'NUMBER_OF_REVIEWS', 'NUMBER_OF_REVIEWS_LTM', 'FIRST_REVIEW', 'LAST_REVIEW', 'REVIEW_SCORES_RATING', 'REVIEW_SCORES_ACCURACY', 'REVIEW_SCORES_CLEANLINESS', 'REVIEW_SCORES_CHECKIN', 'REVIEW_SCORES_COMMUNICATION', 'REVIEW_SCORES_LOCATION', 'REVIEW_SCORES_VALUE', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY', 'CANCELLATION_POLICY', 'REVIEWS_PER_MONTH']

In [9]:
df_cambridge = df_cambridge.drop(['ID', 'LISTING_URL', 'SCRAPE_ID', 'LAST_SCRAPED', 'NAME', 'SUMMARY', 'SPACE', 'DESCRIPTION', 'EXPERIENCES_OFFERED', 'NEIGHBORHOOD_OVERVIEW', 'NOTES', 'TRANSIT', 'ACCESS', 'INTERACTION', 'HOUSE_RULES', 'THUMBNAIL_URL', 'MEDIUM_URL', 'PICTURE_URL', 'XL_PICTURE_URL', 'HOST_URL', 'HOST_NAME', 'HOST_SINCE', 'HOST_LOCATION', 'HOST_ABOUT', 'HOST_THUMBNAIL_URL', 'HOST_PICTURE_URL', 'HOST_NEIGHBOURHOOD', 'HOST_VERIFICATIONS', 'STREET', 'NEIGHBOURHOOD', 'NEIGHBOURHOOD_CLEANSED', 'NEIGHBOURHOOD_GROUP_CLEANSED', 'CITY', 'STATE', 'ZIPCODE', 'MARKET', 'SMART_LOCATION', 'COUNTRY_CODE', 'COUNTRY', 'IS_LOCATION_EXACT', 'CALENDAR_UPDATED', 'HAS_AVAILABILITY', 'CALENDAR_LAST_SCRAPED', 'REQUIRES_LICENSE', 'LICENSE', 'JURISDICTION_NAMES', 'REQUIRE_GUEST_PROFILE_PICTURE', 'REQUIRE_GUEST_PHONE_VERIFICATION', 'CALCULATED_HOST_LISTINGS_COUNT', 'CALCULATED_HOST_LISTINGS_COUNT_ENTIRE_HOMES', 'CALCULATED_HOST_LISTINGS_COUNT_PRIVATE_ROOMS', 'CALCULATED_HOST_LISTINGS_COUNT_SHARED_ROOMS'], axis=1)
print(df_cambridge.columns.to_list())

['HOST_ID', 'HOST_RESPONSE_TIME', 'HOST_RESPONSE_RATE', 'HOST_ACCEPTANCE_RATE', 'HOST_IS_SUPERHOST', 'HOST_LISTINGS_COUNT', 'HOST_TOTAL_LISTINGS_COUNT', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'LATITUDE', 'LONGITUDE', 'PROPERTY_TYPE', 'ROOM_TYPE', 'ACCOMMODATES', 'BATHROOMS', 'BEDROOMS', 'BEDS', 'BED_TYPE', 'AMENITIES', 'SQUARE_FEET', 'PRICE', 'WEEKLY_PRICE', 'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE', 'GUESTS_INCLUDED', 'EXTRA_PEOPLE', 'MINIMUM_NIGHTS', 'MAXIMUM_NIGHTS', 'MINIMUM_MINIMUM_NIGHTS', 'MAXIMUM_MINIMUM_NIGHTS', 'MINIMUM_MAXIMUM_NIGHTS', 'MAXIMUM_MAXIMUM_NIGHTS', 'MINIMUM_NIGHTS_AVG_NTM', 'MAXIMUM_NIGHTS_AVG_NTM', 'AVAILABILITY_30', 'AVAILABILITY_60', 'AVAILABILITY_90', 'AVAILABILITY_365', 'NUMBER_OF_REVIEWS', 'NUMBER_OF_REVIEWS_LTM', 'FIRST_REVIEW', 'LAST_REVIEW', 'REVIEW_SCORES_RATING', 'REVIEW_SCORES_ACCURACY', 'REVIEW_SCORES_CLEANLINESS', 'REVIEW_SCORES_CHECKIN', 'REVIEW_SCORES_COMMUNICATION', 'REVIEW_SCORES_LOCATION', 'REVIEW_SCORES_VALUE', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY', 'CANCELLATION_POLICY', 'REVIEWS_PER_MONTH']

### Dropping identical rows

In [10]:
# count number of duplicated rows
num_duplicates = len(df_boston) - len(df_boston.drop_duplicates())

# drop duplicated rows
df_boston.drop_duplicates(inplace=True)

# count number of rows dropped
num_dropped = num_duplicates

print("Number of duplicated rows dropped: ", num_dropped)

Number of duplicated rows dropped:  0

In [11]:
# count number of duplicated rows
num_duplicates = len(df_cambridge) - len(df_cambridge.drop_duplicates())

# drop duplicated rows
df_cambridge.drop_duplicates(inplace=True)

# count number of rows dropped
num_dropped = num_duplicates

print("Number of duplicated rows dropped: ", num_dropped)

Number of duplicated rows dropped:  0

### Displaying our new columns names

In [12]:
print(df_boston.columns.to_list())

['HOST_ID', 'HOST_RESPONSE_TIME', 'HOST_RESPONSE_RATE', 'HOST_ACCEPTANCE_RATE', 'HOST_IS_SUPERHOST', 'HOST_LISTINGS_COUNT', 'HOST_TOTAL_LISTINGS_COUNT', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'LATITUDE', 'LONGITUDE', 'PROPERTY_TYPE', 'ROOM_TYPE', 'ACCOMMODATES', 'BATHROOMS', 'BEDROOMS', 'BEDS', 'BED_TYPE', 'AMENITIES', 'SQUARE_FEET', 'PRICE', 'WEEKLY_PRICE', 'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE', 'GUESTS_INCLUDED', 'EXTRA_PEOPLE', 'MINIMUM_NIGHTS', 'MAXIMUM_NIGHTS', 'MINIMUM_MINIMUM_NIGHTS', 'MAXIMUM_MINIMUM_NIGHTS', 'MINIMUM_MAXIMUM_NIGHTS', 'MAXIMUM_MAXIMUM_NIGHTS', 'MINIMUM_NIGHTS_AVG_NTM', 'MAXIMUM_NIGHTS_AVG_NTM', 'AVAILABILITY_30', 'AVAILABILITY_60', 'AVAILABILITY_90', 'AVAILABILITY_365', 'NUMBER_OF_REVIEWS', 'NUMBER_OF_REVIEWS_LTM', 'FIRST_REVIEW', 'LAST_REVIEW', 'REVIEW_SCORES_RATING', 'REVIEW_SCORES_ACCURACY', 'REVIEW_SCORES_CLEANLINESS', 'REVIEW_SCORES_CHECKIN', 'REVIEW_SCORES_COMMUNICATION', 'REVIEW_SCORES_LOCATION', 'REVIEW_SCORES_VALUE', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY', 'CANCELLATION_POLICY', 'REVIEWS_PER_MONTH']

In [13]:
print(df_cambridge.columns.to_list())

['HOST_ID', 'HOST_RESPONSE_TIME', 'HOST_RESPONSE_RATE', 'HOST_ACCEPTANCE_RATE', 'HOST_IS_SUPERHOST', 'HOST_LISTINGS_COUNT', 'HOST_TOTAL_LISTINGS_COUNT', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'LATITUDE', 'LONGITUDE', 'PROPERTY_TYPE', 'ROOM_TYPE', 'ACCOMMODATES', 'BATHROOMS', 'BEDROOMS', 'BEDS', 'BED_TYPE', 'AMENITIES', 'SQUARE_FEET', 'PRICE', 'WEEKLY_PRICE', 'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE', 'GUESTS_INCLUDED', 'EXTRA_PEOPLE', 'MINIMUM_NIGHTS', 'MAXIMUM_NIGHTS', 'MINIMUM_MINIMUM_NIGHTS', 'MAXIMUM_MINIMUM_NIGHTS', 'MINIMUM_MAXIMUM_NIGHTS', 'MAXIMUM_MAXIMUM_NIGHTS', 'MINIMUM_NIGHTS_AVG_NTM', 'MAXIMUM_NIGHTS_AVG_NTM', 'AVAILABILITY_30', 'AVAILABILITY_60', 'AVAILABILITY_90', 'AVAILABILITY_365', 'NUMBER_OF_REVIEWS', 'NUMBER_OF_REVIEWS_LTM', 'FIRST_REVIEW', 'LAST_REVIEW', 'REVIEW_SCORES_RATING', 'REVIEW_SCORES_ACCURACY', 'REVIEW_SCORES_CLEANLINESS', 'REVIEW_SCORES_CHECKIN', 'REVIEW_SCORES_COMMUNICATION', 'REVIEW_SCORES_LOCATION', 'REVIEW_SCORES_VALUE', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY', 'CANCELLATION_POLICY', 'REVIEWS_PER_MONTH']

# Separate numerical data

In [14]:
numerical_data_b = df_boston.select_dtypes(include=[np.number])
numerical_data_b

,HOST_ID,HOST_ACCEPTANCE_RATE,HOST_LISTINGS_COUNT,HOST_TOTAL_LISTINGS_COUNT,LATITUDE,LONGITUDE,ACCOMMODATES,BATHROOMS,BEDROOMS,BEDS,...,NUMBER_OF_REVIEWS,NUMBER_OF_REVIEWS_LTM,REVIEW_SCORES_RATING,REVIEW_SCORES_ACCURACY,REVIEW_SCORES_CLEANLINESS,REVIEW_SCORES_CHECKIN,REVIEW_SCORES_COMMUNICATION,REVIEW_SCORES_LOCATION,REVIEW_SCORES_VALUE,REVIEWS_PER_MONTH
0,8229,NaN,6.0,6.0,42.32981,-71.09559,2,1.0,1.0,1.0,...,106,26,95.0,10.0,10.0,10.0,10.0,9.0,10.0,0.81
1,8229,NaN,6.0,6.0,42.32994,-71.09351,4,1.0,1.0,2.0,...,115,30,96.0,10.0,10.0,10.0,10.0,9.0,10.0,0.91
2,26988,NaN,12.0,12.0,42.35919,-71.06265,2,1.0,1.0,1.0,...,24,3,93.0,9.0,9.0,10.0,10.0,10.0,9.0,0.37
3,26988,NaN,12.0,12.0,42.35840,-71.06185,2,1.0,1.0,1.0,...,30,3,95.0,10.0,9.0,10.0,10.0,10.0,9.0,0.24
4,38997,NaN,11.0,11.0,42.34973,-71.08792,3,1.0,0.0,1.0,...,9,2,87.0,9.0,9.0,9.0,8.0,10.0,9.0,0.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3502,266312920,NaN,24.0,24.0,42.36528,-71.11290,8,1.5,3.0,4.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3503,276272964,NaN,2.0,2.0,42.30989,-71.08437,8,1.0,4.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3504,96961013,NaN,22.0,22.0,42.33697,-71.15169,2,1.0,0.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3505,96961013,NaN,22.0,22.0,42.33697,-71.15169,4,1.0,1.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3506,266312920,NaN,24.0,24.0,42.33697,-71.15169,6,1.0,2.0,3.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
numerical_data_c = df_cambridge.select_dtypes(include=[np.number])
numerical_data_c

,HOST_ID,HOST_ACCEPTANCE_RATE,HOST_LISTINGS_COUNT,HOST_TOTAL_LISTINGS_COUNT,LATITUDE,LONGITUDE,ACCOMMODATES,BATHROOMS,BEDROOMS,BEDS,...,NUMBER_OF_REVIEWS,NUMBER_OF_REVIEWS_LTM,REVIEW_SCORES_RATING,REVIEW_SCORES_ACCURACY,REVIEW_SCORES_CLEANLINESS,REVIEW_SCORES_CHECKIN,REVIEW_SCORES_COMMUNICATION,REVIEW_SCORES_LOCATION,REVIEW_SCORES_VALUE,REVIEWS_PER_MONTH
0,306681,NaN,3.0,3.0,42.38329,-71.13617,5,1.0,2,2.0,...,33,4,95.0,10.0,10.0,10.0,10.0,10.0,9.0,0.26
1,40965,NaN,3.0,3.0,42.39469,-71.13223,3,1.0,1,1.0,...,144,3,95.0,9.0,9.0,10.0,10.0,10.0,10.0,1.22
2,40965,NaN,3.0,3.0,42.39454,-71.13431,1,1.0,1,1.0,...,33,1,98.0,9.0,10.0,10.0,10.0,10.0,10.0,0.27
3,74249,NaN,3.0,3.0,42.36276,-71.09765,1,1.0,1,1.0,...,6,0,80.0,8.0,9.0,8.0,10.0,10.0,8.0,0.05
4,84280,NaN,1.0,1.0,42.38670,-71.12387,2,2.5,1,1.0,...,82,23,96.0,10.0,10.0,10.0,10.0,10.0,10.0,0.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1272,55480078,NaN,3.0,3.0,42.36452,-71.07888,4,1.0,1,3.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1273,4208980,NaN,1.0,1.0,42.36254,-71.11145,3,1.5,2,2.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1274,93155711,NaN,0.0,0.0,42.37060,-71.08737,2,1.0,1,NaN,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1275,93155711,NaN,0.0,0.0,42.37108,-71.08634,2,1.0,1,1.0,...,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.00
1276,311628721,NaN,1.0,1.0,42.34875,-71.10711,6,1.0,2,3.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Separate categorical data

In [16]:
categorical_data_b = df_boston.select_dtypes(include=[object])
categorical_data_b

,HOST_RESPONSE_TIME,HOST_RESPONSE_RATE,HOST_IS_SUPERHOST,HOST_HAS_PROFILE_PIC,HOST_IDENTITY_VERIFIED,PROPERTY_TYPE,ROOM_TYPE,BED_TYPE,AMENITIES,PRICE,WEEKLY_PRICE,MONTHLY_PRICE,SECURITY_DEPOSIT,CLEANING_FEE,EXTRA_PEOPLE,FIRST_REVIEW,LAST_REVIEW,INSTANT_BOOKABLE,IS_BUSINESS_TRAVEL_READY,CANCELLATION_POLICY
0,within an hour,100%,f,t,t,Guest suite,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$145.00,$980.00,"$3,000.00",$0.00,$60.00,$0.00,2009-03-21,2019-10-31,t,f,strict_14_with_grace_period
1,within an hour,100%,f,t,t,Condominium,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$169.00,NaN,NaN,$0.00,$80.00,$8.00,2009-08-06,2019-11-02,t,f,strict_14_with_grace_period
2,within a few hours,100%,t,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$99.00,"$1,200.00","$2,900.00","$1,000.00",$250.00,$0.00,2014-08-12,2019-09-30,f,f,strict_14_with_grace_period
3,within a few hours,100%,t,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$150.00,"$1,200.00","$3,000.00","$1,000.00",$250.00,$0.00,2009-09-21,2019-09-14,f,f,strict_14_with_grace_period
4,within an hour,100%,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$84.00,NaN,"$2,250.00",$500.00,$150.00,$0.00,2016-01-09,2019-07-22,f,f,strict_14_with_grace_period
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3502,within an hour,100%,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",$250.00,NaN,NaN,$500.00,$175.00,$20.00,NaN,NaN,t,f,strict_14_with_grace_period
3503,NaN,NaN,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,Breakfast,...",$300.00,NaN,NaN,NaN,NaN,$0.00,NaN,NaN,t,f,flexible
3504,within an hour,100%,t,t,f,Condominium,Entire home/apt,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",$120.00,NaN,NaN,$500.00,$150.00,$0.00,NaN,NaN,t,f,strict_14_with_grace_period
3505,within an hour,100%,t,t,f,Condominium,Entire home/apt,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,""Free stre...",$150.00,NaN,NaN,$500.00,$120.00,$20.00,NaN,NaN,t,f,strict_14_with_grace_period
3506,within an hour,100%,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",$200.00,NaN,NaN,$500.00,$165.00,$25.00,NaN,NaN,t,f,strict_14_with_grace_period

In [17]:
categorical_data_c = df_cambridge.select_dtypes(include=[object])
categorical_data_c

,HOST_RESPONSE_TIME,HOST_RESPONSE_RATE,HOST_IS_SUPERHOST,HOST_HAS_PROFILE_PIC,HOST_IDENTITY_VERIFIED,PROPERTY_TYPE,ROOM_TYPE,BED_TYPE,AMENITIES,PRICE,WEEKLY_PRICE,MONTHLY_PRICE,SECURITY_DEPOSIT,CLEANING_FEE,EXTRA_PEOPLE,FIRST_REVIEW,LAST_REVIEW,INSTANT_BOOKABLE,IS_BUSINESS_TRAVEL_READY,CANCELLATION_POLICY
0,within a few hours,100%,f,t,t,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$200.00,"$1,300.00","$3,900.00",$500.00,$50.00,$20.00,2009-07-23,2019-06-09,f,f,strict_14_with_grace_period
1,within an hour,100%,t,t,t,House,Private room,Real Bed,"{""Cable TV"",Wifi,""Air conditioning"",""Pets live...",$105.00,$600.00,"$2,400.00",$0.00,$0.00,$25.00,2010-03-30,2019-09-01,f,f,strict_14_with_grace_period
2,within an hour,100%,t,t,t,Condominium,Private room,Futon,"{""Cable TV"",Internet,Wifi,""Air conditioning"",""...",$75.00,$450.00,"$1,500.00",$0.00,$0.00,$25.00,2009-11-14,2019-04-14,f,f,strict_14_with_grace_period
3,within an hour,100%,t,t,t,Bed and breakfast,Private room,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$185.00,$750.00,"$2,125.00",$0.00,$45.00,$20.00,2010-03-06,2018-08-04,f,f,strict_14_with_grace_period
4,within an hour,100%,t,t,f,House,Private room,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",$120.00,$700.00,NaN,NaN,NaN,$30.00,2012-05-14,2019-11-08,f,f,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1272,within an hour,97%,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,Breakfast,...",$189.00,NaN,NaN,$0.00,$50.00,$25.00,NaN,NaN,t,f,moderate
1273,NaN,NaN,f,t,t,Condominium,Entire home/apt,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,""Free park...",$150.00,NaN,NaN,NaN,NaN,$0.00,NaN,NaN,f,f,moderate
1274,within a few hours,100%,f,t,f,Apartment,Private room,Real Bed,"{Wifi,""Air conditioning"",Kitchen,Heating,Washe...",$50.00,NaN,NaN,NaN,NaN,$0.00,NaN,NaN,f,f,moderate
1275,within a few hours,100%,f,t,f,Apartment,Private room,Real Bed,"{Wifi,""Air conditioning"",Kitchen,""Hot tub"",Hea...",$50.00,NaN,NaN,NaN,NaN,$0.00,2019-11-18,2019-11-18,f,f,moderate
1276,NaN,NaN,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",$125.00,NaN,NaN,$150.00,$80.00,$0.00,NaN,NaN,t,f,moderate



| we can see that the columns containing prices are strings with the comma and dollar sign   |
|-----------------------------------------|

In [18]:
# remove dollar sign and comma from price columns and convert to numerical data
def format_price_columns(dataframe):
    price_columns = ['PRICE', 'WEEKLY_PRICE', 'MONTHLY_PRICE', 'SECURITY_DEPOSIT', 'CLEANING_FEE', 'EXTRA_PEOPLE']
    for col in price_columns:
        dataframe[col] = dataframe[col].apply(lambda x: float(x.replace(',', '').replace('$', '')) if isinstance(x, str) else x)
    return dataframe

In [19]:
df_boston = format_price_columns(df_boston) 
df_cambridge = format_price_columns(df_cambridge)

<h5>get the numerical and categorical columns

In [20]:
#boston
numerical_columns_b = df_boston.select_dtypes(include=['int', 'float'])
categorical_columns_b = df_boston.select_dtypes(include=['object', 'bool'])

#cambridge
numerical_columns_c = df_cambridge.select_dtypes(include=['int', 'float'])
categorical_columns_c = df_cambridge.select_dtypes(include=['object', 'bool'])

### Print the numerical and categorical columns

In [21]:
numerical_columns_b

,HOST_ID,HOST_ACCEPTANCE_RATE,HOST_LISTINGS_COUNT,HOST_TOTAL_LISTINGS_COUNT,LATITUDE,LONGITUDE,ACCOMMODATES,BATHROOMS,BEDROOMS,BEDS,...,NUMBER_OF_REVIEWS,NUMBER_OF_REVIEWS_LTM,REVIEW_SCORES_RATING,REVIEW_SCORES_ACCURACY,REVIEW_SCORES_CLEANLINESS,REVIEW_SCORES_CHECKIN,REVIEW_SCORES_COMMUNICATION,REVIEW_SCORES_LOCATION,REVIEW_SCORES_VALUE,REVIEWS_PER_MONTH
0,8229,NaN,6.0,6.0,42.32981,-71.09559,2,1.0,1.0,1.0,...,106,26,95.0,10.0,10.0,10.0,10.0,9.0,10.0,0.81
1,8229,NaN,6.0,6.0,42.32994,-71.09351,4,1.0,1.0,2.0,...,115,30,96.0,10.0,10.0,10.0,10.0,9.0,10.0,0.91
2,26988,NaN,12.0,12.0,42.35919,-71.06265,2,1.0,1.0,1.0,...,24,3,93.0,9.0,9.0,10.0,10.0,10.0,9.0,0.37
3,26988,NaN,12.0,12.0,42.35840,-71.06185,2,1.0,1.0,1.0,...,30,3,95.0,10.0,9.0,10.0,10.0,10.0,9.0,0.24
4,38997,NaN,11.0,11.0,42.34973,-71.08792,3,1.0,0.0,1.0,...,9,2,87.0,9.0,9.0,9.0,8.0,10.0,9.0,0.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3502,266312920,NaN,24.0,24.0,42.36528,-71.11290,8,1.5,3.0,4.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3503,276272964,NaN,2.0,2.0,42.30989,-71.08437,8,1.0,4.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3504,96961013,NaN,22.0,22.0,42.33697,-71.15169,2,1.0,0.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3505,96961013,NaN,22.0,22.0,42.33697,-71.15169,4,1.0,1.0,1.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3506,266312920,NaN,24.0,24.0,42.33697,-71.15169,6,1.0,2.0,3.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
categorical_columns_b

,HOST_RESPONSE_TIME,HOST_RESPONSE_RATE,HOST_IS_SUPERHOST,HOST_HAS_PROFILE_PIC,HOST_IDENTITY_VERIFIED,PROPERTY_TYPE,ROOM_TYPE,BED_TYPE,AMENITIES,FIRST_REVIEW,LAST_REVIEW,INSTANT_BOOKABLE,IS_BUSINESS_TRAVEL_READY,CANCELLATION_POLICY
0,within an hour,100%,f,t,t,Guest suite,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",2009-03-21,2019-10-31,t,f,strict_14_with_grace_period
1,within an hour,100%,f,t,t,Condominium,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",2009-08-06,2019-11-02,t,f,strict_14_with_grace_period
2,within a few hours,100%,t,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",2014-08-12,2019-09-30,f,f,strict_14_with_grace_period
3,within a few hours,100%,t,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",2009-09-21,2019-09-14,f,f,strict_14_with_grace_period
4,within an hour,100%,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",2016-01-09,2019-07-22,f,f,strict_14_with_grace_period
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3502,within an hour,100%,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",NaN,NaN,t,f,strict_14_with_grace_period
3503,NaN,NaN,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,Breakfast,...",NaN,NaN,t,f,flexible
3504,within an hour,100%,t,t,f,Condominium,Entire home/apt,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",NaN,NaN,t,f,strict_14_with_grace_period
3505,within an hour,100%,t,t,f,Condominium,Entire home/apt,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,""Free stre...",NaN,NaN,t,f,strict_14_with_grace_period
3506,within an hour,100%,f,t,f,Apartment,Entire home/apt,Real Bed,"{TV,""Cable TV"",Wifi,""Air conditioning"",Kitchen...",NaN,NaN,t,f,strict_14_with_grace_period

# Convert binary data to 1's and 0's

In [23]:
binary_columns = ['HOST_IS_SUPERHOST', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY']

for col in binary_columns:
    categorical_columns_b[col] = categorical_columns_b[col].replace({'t': 1, 'f': 0})

print(categorical_columns_b[['HOST_IS_SUPERHOST', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY']])

      HOST_IS_SUPERHOST  HOST_HAS_PROFILE_PIC  HOST_IDENTITY_VERIFIED  \
0                   0.0                   1.0                     1.0
1                   0.0                   1.0                     1.0
2                   1.0                   1.0                     0.0
3                   1.0                   1.0                     0.0
4                   0.0                   1.0                     0.0
...                 ...                   ...                     ...
3502                0.0                   1.0                     0.0
3503                0.0                   1.0                     0.0
3504                1.0                   1.0                     0.0
3505                1.0                   1.0                     0.0
3506                0.0                   1.0                     0.0

      INSTANT_BOOKABLE  IS_BUSINESS_TRAVEL_READY
0                    1                         0
1                    1                         0
2                    0                         0
3                    0                         0
4                    0                         0
...                ...                       ...
3502                 1                         0
3503                 1                         0
3504                 1                         0
3505                 1                         0
3506                 1                         0

[3507 rows x 5 columns]

In [24]:
binary_columns = ['HOST_IS_SUPERHOST', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY']

for col in binary_columns:
    categorical_columns_c[col] = categorical_columns_c[col].replace({'t': 1, 'f': 0})

print(categorical_columns_c[['HOST_IS_SUPERHOST', 'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY']])

      HOST_IS_SUPERHOST  HOST_HAS_PROFILE_PIC  HOST_IDENTITY_VERIFIED  \
0                   0.0                   1.0                     1.0
1                   1.0                   1.0                     1.0
2                   1.0                   1.0                     1.0
3                   1.0                   1.0                     1.0
4                   1.0                   1.0                     0.0
...                 ...                   ...                     ...
1272                0.0                   1.0                     0.0
1273                0.0                   1.0                     1.0
1274                0.0                   1.0                     0.0
1275                0.0                   1.0                     0.0
1276                0.0                   1.0                     0.0

      INSTANT_BOOKABLE  IS_BUSINESS_TRAVEL_READY
0                    0                         0
1                    0                         0
2                    0                         0
3                    0                         0
4                    0                         0
...                ...                       ...
1272                 1                         0
1273                 0                         0
1274                 0                         0
1275                 0                         0
1276                 1                         0

[1277 rows x 5 columns]

In [25]:
categorical_columns_b.columns

Index(['HOST_RESPONSE_TIME', 'HOST_RESPONSE_RATE', 'HOST_IS_SUPERHOST',
       'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'PROPERTY_TYPE',
       'ROOM_TYPE', 'BED_TYPE', 'AMENITIES', 'FIRST_REVIEW', 'LAST_REVIEW',
       'INSTANT_BOOKABLE', 'IS_BUSINESS_TRAVEL_READY', 'CANCELLATION_POLICY'],
      dtype='object')

# One-hot encoded

In [26]:
# specify the columns to be one-hot encoded
cols_to_encode = ['HOST_RESPONSE_TIME', 'HOST_RESPONSE_RATE', 'HOST_IS_SUPERHOST',
                  'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'AMENITIES',
                  'FIRST_REVIEW', 'LAST_REVIEW', 'INSTANT_BOOKABLE',
                  'IS_BUSINESS_TRAVEL_READY']

# perform one-hot encoding
categorical_columns_b = pd.get_dummies(categorical_columns_b, columns=cols_to_encode)

# view the resulting dataframe
categorical_columns_b.columns

Index(['PROPERTY_TYPE', 'ROOM_TYPE', 'BED_TYPE', 'CANCELLATION_POLICY',
       'HOST_RESPONSE_TIME_a few days or more',
       'HOST_RESPONSE_TIME_within a day',
       'HOST_RESPONSE_TIME_within a few hours',
       'HOST_RESPONSE_TIME_within an hour', 'HOST_RESPONSE_RATE_0%',
       'HOST_RESPONSE_RATE_100%',
       ...
       'LAST_REVIEW_2019-11-27', 'LAST_REVIEW_2019-11-28',
       'LAST_REVIEW_2019-11-29', 'LAST_REVIEW_2019-11-30',
       'LAST_REVIEW_2019-12-01', 'LAST_REVIEW_2019-12-02',
       'LAST_REVIEW_2019-12-03', 'INSTANT_BOOKABLE_0', 'INSTANT_BOOKABLE_1',
       'IS_BUSINESS_TRAVEL_READY_0'],
      dtype='object', length=4600)

In [27]:
# specify the columns to be one-hot encoded
cols_to_encode = ['HOST_RESPONSE_TIME', 'HOST_RESPONSE_RATE', 'HOST_IS_SUPERHOST',
                  'HOST_HAS_PROFILE_PIC', 'HOST_IDENTITY_VERIFIED', 'AMENITIES',
                  'FIRST_REVIEW', 'LAST_REVIEW', 'INSTANT_BOOKABLE',
                  'IS_BUSINESS_TRAVEL_READY']

# perform one-hot encoding
categorical_columns_c = pd.get_dummies(categorical_columns_c, columns=cols_to_encode)

# view the resulting dataframe
categorical_columns_c.columns

Index(['PROPERTY_TYPE', 'ROOM_TYPE', 'BED_TYPE', 'CANCELLATION_POLICY',
       'HOST_RESPONSE_TIME_a few days or more',
       'HOST_RESPONSE_TIME_within a day',
       'HOST_RESPONSE_TIME_within a few hours',
       'HOST_RESPONSE_TIME_within an hour', 'HOST_RESPONSE_RATE_0%',
       'HOST_RESPONSE_RATE_100%',
       ...
       'LAST_REVIEW_2019-11-19', 'LAST_REVIEW_2019-11-20',
       'LAST_REVIEW_2019-11-21', 'LAST_REVIEW_2019-11-22',
       'LAST_REVIEW_2019-11-23', 'LAST_REVIEW_2019-11-24',
       'LAST_REVIEW_2019-11-25', 'INSTANT_BOOKABLE_0', 'INSTANT_BOOKABLE_1',
       'IS_BUSINESS_TRAVEL_READY_0'],
      dtype='object', length=2293)

# Merge dataframes

In [28]:
cleaned_df_b = pd.concat([numerical_data_b, categorical_data_b], axis=1)
cleaned_df_c = pd.concat([numerical_data_c, categorical_data_c], axis=1)

# Export

In [29]:
cleaned_df_b.to_csv('./results/cleaned_boston.csv', index=False)
cleaned_df_c.to_csv('./results/cleaned_cambridge.csv', index=False)